### ISSUE TITLE
No valid training data were found

### ISSUE THREAD

**Issue by SFrav** [GianniCristian/GEEUrbanExtent#1]
I get an error when generating most maplayers at the end of this script. The error states that "No valid training data were found".

After some manipulation of the CSVs, GEE ingested them and they seem to plot okay.
I tried adding `var cities_table = ee.FeatureCollection ...` to the script but this did not help. I also tried entering different cities to the `var selectedCities`

What I ultimately want to do is detect buildings in rural Africa and compare the results with the [World Settlement Footprint and the Global Urban Footprint](https://urban-tep.eu/#!pages/dataservices). My training data for this would be many individual buildings rather than whole cities.
First, though, I want to replicate this analysis.

**Comment by GianniCristian** [comment]
Hi, could you please share the code? You can get the sharing link by clicking on the 'Get Link' button above the script.

**Comment by SFrav** [comment]
Thanks for the quick reply. [Here's the link](https://code.earthengine.google.com/48d9ff27d3bb7403173952f89d2ac0fc).

**Comment by GianniCristian** [comment]
Hi SFrav,

sorry for the delay. Finally I found the time to look on it in more detail. The main issue was that GEE changed, and there was no compatibility with the current version of the code. 

I modified and fixed the issue. You can find on the homepage how to prepare/install the new code. 

I did myself and it works: [LINK](https://code.earthengine.google.com/2f4e3bf5133b4ceeac6a694b9e07ad13)

Please let me know if you get any issue.

**Comment by SFrav** [comment]
Thanks for all the work on rewriting that. Excellent commenting too.
The link doesn't work, but I set it up in my EE environment. I get one minor error related to the autoCentreMap function. Commenting the function and the function call does the job for now.
However, I get the following error when trying to run the code on Rio de Janeiro: `Closing + Opening: Layer error: Collection.geometry: Error in map(ID=null):
Geometry.containedIn: Unable to perform this geometry operation. Please specify a non-zero error margin.`
I have the right city for the variable `selectedCities` and a wide catchment around Rio. There are 12 S2 images for the time period.
If I can see your example then I will be able to troubleshoot. If you use the getlink option to share your example, that would be great. Thanks!

**Comment by SFrav** [comment]
Ok. Working my way up the coast, there are S2 images in that time period for Rio. Now the error is as follows: `Closing + Opening: Layer error: No valid training data were found.`

**Comment by GianniCristian** [comment]
I fixed the link (there was a dot typo at the end of the URL). To make it work on your workplace, you should change the uploaded table to the one of your asset. 

Please let me know.

**Comment by SFrav** [comment]
Great. Yes, that's done the job.
Thanks!

**Comment by Apintonascimento** [comment]
Olá, bom dia. Estou com este mesmo erro no meu script e gostaria de saber o que acontece para dar este erro ?
O erro é: No valid training data were found.
Se alguém puder me ajudar, serei grata.
